### ISSUE TITLE
Add SPI-Provider to all wrapped bundles with SPI services

### ISSUE THREAD

**Issue by essobedo** [apache/camel-karaf#289]
By default, a bundle that is created thanks to the wrap protocol doesn't have the manifest entry properly `SPI-Provider` set. The goal of this task is to check each jar that is wrapped if it has some SPI services defined into `META-INF/services` and if so add `SPI-Provider=*` to the Wrap URI and also add the spifly feature as prerequisite feature dependency

**Comment by jbonofre** [comment]
NB: there is a SPI feature in Karaf directly that should be installed to work with SPI.
