### ISSUE TITLE
CamelAws2IamITest is failing on the test container

### ISSUE THREAD

**Issue by jbonofre** [apache/camel-karaf#431]
The itest seems to require specific resource:

```
[tc.localstack/localstack:3.4.0] ERROR : Could not start container
com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"content digest sha256:dcae4711247195b3eb01a1ffe6ea1ad9a19199d9441eff86d3a4b4aa3f49d4c6: not found"}
```

This should be avoided or at least documented.

**Comment by jbonofre** [comment]
@essobedo @f2par0 ^^

**Comment by f2par0** [comment]
Hello @jbonofre , I cannot reproduce the error locally , and the latest build on this PR for instance https://github.com/apache/camel-karaf/pull/433/checks   shows a successful test

```CamelAws2IamITest: testResultMock
bundle:list -s -t 0 | grep camel-aws2-iam-test
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 40.09 s -- in org.apache.karaf.camel.itest.CamelAws2IamITest
```

Do you reproduce this  ?

**Comment by jbonofre** [comment]
@f2par0 it seems to work on MacOS Intel platform but not on M1. Maybe related to the default platform used for the test container. I'm investigating.

**Comment by essobedo** [comment]
I cannot reproduce on M3

**Comment by jbonofre** [comment]
I'm trying a new time but it seems to be fixed.

**Comment by jbonofre** [comment]
I still have the issue on M3 where the build is "stuck" on:

```
provider org.apache.maven.surefire.junit4.JUnit4Provider
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.karaf.camel.itest.CamelAws2IamITest
```

Not a big deal, I can skip this test, but it's weird.

**Comment by essobedo** [comment]
We could skip the test like for LevelDB https://github.com/apache/camel-karaf/pull/521. If it is ok, for you I can do it within the context of this ticket

**Comment by jbonofre** [comment]
Maybe we can introduce a profile to skip (we can keep it on GH Actions and give option to users to skip on some platform).
