### ISSUE TITLE
The log level of the integration test for the drill feature should not be DEBUG

### ISSUE THREAD

**Issue by essobedo** [apache/camel-karaf#452]
It appears that the log level used for the camel-drill feature is DEBUG while INFO is expected which fills up the log file

**Comment by stataru8** [comment]
I've tried to get this fixed, but I'm running out of ideas
1. the logs causing the spam aren't coming from the Apache Drill container
2. adding `log4j2.xml` or `logback.xml` to the classpath + corresponding dependencies makes a difference, but the logs causing the spam aren't affected
3. the logs causing the spam originate from the package `oadd.*` -> https://github.com/apache/drill/blob/drill-1.21.2/exec/jdbc-all/pom.xml#L35 -> `<bundle dependency='true'>wrap:mvn:org.apache.drill.exec/drill-jdbc-all/${apache-drill-version}$Export-Package=org.apache.drill.jdbc.*;version=${apache-drill-version}&amp;SPI-Provider=java.sql.Driver</bundle>`
    a. not sure if this is messing up something https://github.com/apache/drill/blob/drill-1.21.2/exec/jdbc-all/pom.xml#L645
    b. manually deleting the log4j package from the drill-jdbc-all-1.21.2.jar in my local Maven repo didn't have any effect

**Comment by stataru8** [comment]
I still haven't found a solution for this. Here is what I have discovered so far:
- the logs causing the spam aren't coming from the Apache Drill container
- adding `log4j2.xml` or `logback.xml` to the classpath + corresponding dependencies makes a difference, but the logs causing the spam aren't affected
- the logs causing the spam originate from the package `oadd.*` -> https://github.com/apache/drill/blob/drill-1.21.2/exec/jdbc-all/pom.xml#L35, `<bundle dependency='true'>wrap:mvn:org.apache.drill.exec/drill-jdbc-all/${apache-drill-version}$Export-Package=org.apache.drill.jdbc.*;version=${apache-drill-version}&amp;SPI-Provider=java.sql.Driver</bundle>`
- manually deleting the logback package, `ch` folder, from `drill-jdbc-all-1.21.2.jar` worked

**Comment by stataru8** [comment]
Interestingly enough, having this in the integration test classes breaks the test
```
System.setProperty("logback.configurationFile", ".../logback-test.xml");
```
