### ISSUE TITLE
unexisting groovy version in main pom

### ISSUE THREAD

**Issue by ivan-ra** [apache/camel-karaf#477]
main pom.xml contains wrong groovy version
`<groovy-version>4.0.22</groovy-version>`
It should be 3.0.22

**Comment by oscerd** [comment]
It's here: https://mvnrepository.com/artifact/org.apache.groovy/groovy-all/4.0.22

**Comment by ivan-ra** [comment]
I see, package was changed for 4th groovy. Thanks
