### ISSUE TITLE
Unavailability of Camel-Karaf artifacts on Maven Central

### ISSUE THREAD

**Issue by elishaebenezer** [apache/camel-karaf#497]
I'm coming here as I couldn't find any reliable source (during my search) as to why the latest camel Karaf components aren't available on Maven Central Repo.

I do see that Camel Karaf is tagged with 4.7.0 in GitHub. However, I'm unable to locate this in any publicly available Maven Repositories.

Please advise.

**Comment by jbonofre** [comment]
It's available on Maven Central: https://repo1.maven.org/maven2/org/apache/camel/karaf/apache-camel/4.7.0/
